layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    archived: false
    projects:
    - marsop.github.io
    - machikoro

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: alberto-gregorio-0471122a
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: 1475643
  # telegram: your_username
  twitter: marsop_
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Machine Learning
    web_url: https://www.tensorflow.org/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/tensorflow/tensorflow.png
  
  - name: Reactive Programming
    web_url: http://reactivex.io/
    image_url: https://avatars2.githubusercontent.com/u/984368?s=280&v=4

  - name: Functional Programming
    web_url: https://docs.microsoft.com/en-us/dotnet/fsharp/
    image_url: https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Fsharp%2C_Logomark%2C_October_2014.svg/180px-Fsharp%2C_Logomark%2C_October_2014.svg.png

  - name: Python
    web_url: https://gto76.github.io/python-cheatsheet/
    image_url: https://yt3.ggpht.com/a-/AAuE7mBb9nkPTRX6_g9r_79DVRiNDS0AAkzJwna_kw=s288-mo-c-c0xffffffff-rj-k-no
    

theme: jekyll-theme-midnight
